export default function Head() {
	return (
		<>
			<title>Day 03 - Cryptocurrency Rate Viewer</title>
			<meta
				content="width=device-width, initial-scale=1"
				name="viewport"
			/>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
		</>
	)
}
